#!/usr/bin/python3
"""Fabric script to deploy archive to web servers.

**Expects:** Archive generated by 1-pack_web_static.py

**Deploys to:**
- web-01.aciel.tech
- web-02.aciel.tech (defined in env.hosts)
"""

from fabric.api import put, run, env
from os.path import exists
env.hosts = ['54.237.217.113', '100.26.171.135']


def do_deploy(archive_path):
    """distributes archived files to the web servers"""
    if exists(archive_path) is False:
        return False
    try:
        file_name = archive_path.split("/")[-1]
        file_no_ext = file_name.split(".")[0]
        path = "/data/web_static/releases/"
        put(archive_path, '/tmp/')
        run('mkdir -p {}{}/'.format(path, file_no_ext))
        run('tar -xzf /tmp/{} -C {}{}/'.format(file_name, path, file_no_ext))
        run('rm /tmp/{}'.format(file_name))
        run('mv {0}{1}/web_static/* {0}{1}/'.format(path, file_no_ext))
        run('rm -rf {}{}/web_static'.format(path, file_no_ext))
        run('rm -rf /data/web_static/current')
        run('ln -s {}{}/ /data/web_static/current'.format(path, file_no_ext))
        return True
    except:
        return False
